import type { Friend, ChatMessage, StudySession, User, StudyGroup, Meeting } from '../types';

export const mockUser: User = {
  id: 'user-1',
  username: 'alexj_student',
  email: 'alex@example.com',
  bio: 'Computer Science student passionate about AI and machine learning. Love studying with friends!',
  dateOfBirth: new Date('2002-03-15'),
  school: 'MIT',
  studyField: 'Computer Science',
  graduationDate: new Date('2025-06-15'),
  grade: 'Junior',
  isPublic: true,
  totalStudyTime: 480, // 8 hours
  currentStreak: 5,
  interests: ['Cars', 'Mathematics', 'Programming'],
  joinDate: new Date('2024-01-15'),
};

export const mockFriends: Friend[] = [
  {
    id: 'friend-1',
    name: 'Sarah Chen',
    totalStudyTime: 720,
    isOnline: true,
  },
  {
    id: 'friend-2',
    name: 'Mike Rodriguez',
    totalStudyTime: 360,
    isOnline: false,
    lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'friend-3',
    name: 'Emma Thompson',
    totalStudyTime: 15,
    isOnline: true,
  },
  {
    id: 'friend-4',
    name: 'David Kim',
    totalStudyTime: 590,
    isOnline: false,
    lastSeen: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    userId: 'friend-1',
    userName: 'Sarah Chen',
    message: 'Hey everyone! Just finished a great calculus study session. Anyone want to review derivatives together?',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    type: 'text',
    groupId: 'group-1',
  },
  {
    id: 'msg-2',
    userId: 'friend-2',
    userName: 'Mike Rodriguez',
    message: 'Found this amazing resource for organic chemistry reactions. Super helpful for understanding mechanisms!',
    timestamp: new Date(Date.now() - 25 * 60 * 1000),
    type: 'resource',
    groupId: 'group-2',
  },
  {
    id: 'msg-3',
    userId: 'user-1',
    userName: 'Alex Johnson',
    message: 'Quick note: Remember that integration by parts formula is ∫u dv = uv - ∫v du',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    type: 'note',
    groupId: 'group-1',
  },
  {
    id: 'msg-4',
    userId: 'friend-4',
    userName: 'David Kim',
    message: 'Thanks for the notes! Video call at 3 PM to go over the physics problems?',
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
    type: 'text',
    groupId: 'group-3',
  },
];

export const mockStudySessions: StudySession[] = [
  {
    id: 'session-1',
    userId: 'user-1',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 1 * 60 * 60 * 1000),
    duration: 60,
    subject: 'Mathematics',
  },
  {
    id: 'session-2',
    userId: 'user-1',
    startTime: new Date(Date.now() - 24 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 23 * 60 * 60 * 1000),
    duration: 45,
    subject: 'Programming',
  },
  {
    id: 'session-3',
    userId: 'user-1',
    startTime: new Date(Date.now() - 25 * 60 * 60 * 1000),
    endTime: new Date(Date.now() - 24.5 * 60 * 60 * 1000),
    duration: 30,
    subject: 'History',
  },
];

export const mockStudyGroups: StudyGroup[] = [
  {
    id: 'group-1',
    name: 'Calculus Masters',
    description: 'Advanced calculus study group for final exams',
    subject: 'Mathematics',
    members: ['user-1', 'friend-1', 'friend-3'],
    createdBy: 'friend-1',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isPrivate: false,
    lastActivity: new Date(Date.now() - 15 * 60 * 1000),
    lastMessage: {
      id: 'msg-3',
      userId: 'user-1',
      userName: 'Alex Johnson',
      message: 'Quick note: Remember that integration by parts formula is ∫u dv = uv - ∫v du',
      timestamp: new Date(Date.now() - 15 * 60 * 1000),
      type: 'note',
      groupId: 'group-1',
    },
  },
  {
    id: 'group-2',
    name: 'Chemistry Lab Partners',
    description: 'Organic chemistry study and lab prep',
    subject: 'Chemistry',
    members: ['user-1', 'friend-2', 'friend-4'],
    createdBy: 'friend-2',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isPrivate: false,
    lastActivity: new Date(Date.now() - 25 * 60 * 1000),
    lastMessage: {
      id: 'msg-2',
      userId: 'friend-2',
      userName: 'Mike Rodriguez',
      message: 'Found this amazing resource for organic chemistry reactions. Super helpful for understanding mechanisms!',
      timestamp: new Date(Date.now() - 25 * 60 * 1000),
      type: 'resource',
      groupId: 'group-2',
    },
  },
  {
    id: 'group-3',
    name: 'Physics Problem Solvers',
    description: 'Weekly physics problem solving sessions',
    subject: 'Physics',
    members: ['user-1', 'friend-4'],
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isPrivate: true,
    lastActivity: new Date(Date.now() - 10 * 60 * 1000),
    lastMessage: {
      id: 'msg-4',
      userId: 'friend-4',
      userName: 'David Kim',
      message: 'Thanks for the notes! Video call at 3 PM to go over the physics problems?',
      timestamp: new Date(Date.now() - 10 * 60 * 1000),
      type: 'text',
      groupId: 'group-3',
    },
  },
  {
    id: 'group-4',
    name: 'CS Study Buddies',
    description: 'Computer Science algorithms and data structures',
    subject: 'Computer Science',
    members: ['user-1', 'friend-1', 'friend-3', 'friend-4'],
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    isPrivate: false,
    lastActivity: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'meeting-1',
    title: 'Calculus Study Session',
    description: 'Review integration techniques and practice problems for upcoming exam',
    scheduledTime: new Date(Date.now() + 2 * 60 * 60 * 1000), // 2 hours from now
    duration: 90,
    hostId: 'friend-1',
    participants: ['user-1', 'friend-1', 'friend-3'],
    groupId: 'group-1',
    meetingType: 'video',
    reminders: [15, 60],
    status: 'scheduled',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'meeting-2',
    title: 'Chemistry Lab Prep',
    description: 'Prepare for organic chemistry lab experiment on Friday',
    scheduledTime: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
    duration: 60,
    hostId: 'friend-2',
    participants: ['user-1', 'friend-2', 'friend-4'],
    groupId: 'group-2',
    location: 'Chemistry Building, Room 205',
    meetingType: 'in-person',
    reminders: [30],
    status: 'scheduled',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: 'meeting-3',
    title: 'Physics Problem Review',
    description: 'Go over challenging physics problems from Chapter 12',
    scheduledTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    duration: 45,
    hostId: 'user-1',
    participants: ['user-1', 'friend-4'],
    groupId: 'group-3',
    meetingType: 'phone',
    reminders: [15],
    status: 'scheduled',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
];